# Generated by Django 5.2.7 on 2025-10-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='no_blocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='not_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
